### ISSUE TITLE
404 for https://www.mediamonkey.com/beta/mms/sqlite/node-v64-linux-x64.tar.gz when installing

### ISSUE THREAD

**Issue by BrianVia** [mediamonkeyserver/mms#11]
Been keeping an eye on the releases, excited to see linux has gotten some support as it fits my home setup nicely!  

I was receiving a 404 for the sqlite dependency so i updated that line in the package.json to `"sqlite3": "git+https://github.com/mediamonkeyserver/node-sqlite3.git#master"`, and that allowed me to run npm install.

**Comment by jirihajek** [comment]
I reverted to the original sqlite3 package use, since our didn't have updated sqlite binaries for the latest node versions. Btw, we needed our own sqlite3 in order to create its 'arm' binaries (not provided by the original project yet).

Thanks Brian, look for more feedback from you!
