### ISSUE TITLE
Local IP Address is faulty set by default

### ISSUE THREAD

**Issue by Peke** [mediamonkeyserver/mms#15]
IP address of MMS is faulty set on start and should be set to Local IP or multicast range https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml

My LAN address es corresponds to 192.168.1.0/24

```
==================================================
Running at http://169.254.138.30:10222 (or http://localhost:10222)
Connect using a web browser or using MediaMonkey 5.
==================================================
```

**Comment by LudekStoklasa** [comment]
What's wrong about 169.254.138.30:10222 ?  It is IP of the PC in another network than 192.168.1.0/24.
Are you suggesting that it should list IPs of all available network interfaces?

**Comment by LudekStoklasa** [comment]
Fixed
