### ISSUE TITLE
Configuration changes

### ISSUE THREAD

**Issue by jirihajek** [mediamonkeyserver/mms#24]
1. Configuration is currently stored in DB. It'd probably better be stored directly in filesystem as JSON.

2. Configuration should be available on start-up (i.e. read from filesystem), so that all values (e.g. http port) are available asap. The current dependency on contentDirectoryService is unnecessarily complex and cumbersome.

**Comment by LudekStoklasa** [comment]
Fixed

**Comment by jirihajek** [comment]
1. After the fix, there's `Database loaded in 5 ms` shown even for commands like `mms --status`. Database should only be loaded after these initial commands. I.e. the order should be: 1. Load config, 2. Initialization code, 3. Connect to DB.

2. Related: We should add a command line option to specify a custom DB (and config, etc.) folder. This will be needed e.g. for usage of MMS in a Docker container.

**Comment by LudekStoklasa** [comment]
Fixed
