### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by keinezeit8** [mediamonkeyserver/mms#31]
I have tried installing mms multiple times on different devices.
I followed the instructions in the readme but it always fails with a similar error message.
![image](https://user-images.githubusercontent.com/59264615/78377485-f5c17d80-75cf-11ea-8301-6112f3c33d10.png)
I also tried using a docker, but that also fails (I dont know that much about docker).

I have attached my logfile

[2020-04-03T15_06_31_867Z-debug.log](https://github.com/mediamonkeyserver/mms/files/4428212/2020-04-03T15_06_31_867Z-debug.log)

Maybe I don't know something obvious and that's why it doesn't work, but I just can't get it to install.

I hope this helps with development.

**Comment by jirihajek** [comment]
Sorry, there was an old description, I've just updated it. Just download and unpack https://github.com/mediamonkeyserver/mms/archive/master.zip and run 'npm install' then. Should work fine this way. Thanks for letting us know!

**Comment by keinezeit8** [comment]
I tried it again with the new instructions. this time it seemed to work better, but i still had trouble. It ended again in errors.

[2020-04-24T13_28_37_451Z-debug.log](https://github.com/mediamonkeyserver/mms/files/4529225/2020-04-24T13_28_37_451Z-debug.log)

**Comment by jirihajek** [comment]
Thanks, seems to be an issue with a newer node.js, will look into it (it should work fine with node v8).

Btw, have you tried pre-compiled packages from http://forum.mediamonkey.com/viewtopic.php?f=31&t=90809#p456193 ? These should work right away. Not saying that this issue doesn't need fixing though... ;-)

**Comment by jirihajek** [comment]
Seems to be fixed now. I tested on a generic Linux as I don't have Raspberry Pi here with me, but will hopefully work there as well.
