### ISSUE TITLE
Linebreak style?

### ISSUE THREAD

**Issue by JL102** [mediamonkeyserver/mms#34]
The linebreak style enforced by .eslintrc.js enforces a Unix (LF) style, but all of the js code in this repo seems to already come with Windows (CRLF) style. I thought that maybe it was just VS Code automatically changing it to CRLF. But if I change it to LF to stop the eslint warnings, the file is marked as modified by git; implying that the linebreak style of the files actually are all CRLF. What's up with that?

**Comment by jirihajek** [comment]
Anything new is supposed to have LF, but there are still older files present with CRLF style. We usually change this style as soon as any change is needed in the file, haven't done unification of all the codebase at once (at least not yet).

**Comment by JL102** [comment]
Okay! I'll make sure to commit the LF style changes
