### ISSUE TITLE
DialogLogin causes App to render() around twice every second

### ISSUE THREAD

**Issue by JL102** [mediamonkeyserver/mms#36]
In any other circumstance, App.render() only occurs any time a different page is loaded (e.g. switching from dashboard to collections view), but when DialogLogin is open, the render function repeats ~2x per second

**Comment by jirihajek** [comment]
I wonder whether it might be some issue with withMobileDialog({ breakpoint: 'xs' }), there doesn't seem to be any reason to re-render the dialog frequently.

**Comment by JL102** [comment]
Whoops. Looks like it was my own issue. I added a function that runs every time render() is called, which pings the server and checks login status. Ended up causing a recursive loop (Sets user to null, causes dialogLogin to re-render, causes function to be called again, etc.). Fixed by saving login status as a var inside server.js, and only allowing dialogLogin to open once.
