### ISSUE TITLE
MMS creates audio artifacts

### ISSUE THREAD

**Issue by derritter88** [mediamonkeyserver/mms#48]
When comparing playing music MM5 + SMB mounted network share with music versus MM5 + MMS which is hosted on the server directly the audio quality from the SMB mount is better.

MMS produces audio artifacts while playing.

I have tried flac & mp3 audio files.

Edit: It should not be a bandwith issues as my MM5 test VM uses a dedicated 1 Gbit link while the server uses a 10 Gbit link.

**Comment by jirihajek** [comment]
Interesting, I don't see any reason why'd this happen, particularly as there doesn't seem to be any server-side format conversion involved. I suppose we are talking about some kind of jitter rather than a general audio degradation?

**Comment by derritter88** [comment]
Hi @jirihajek ,

I tried it again and it worked not without any issues.
The issue might occur as I was running MM5 inside a Hyper-V VM.
