### ISSUE TITLE
NAT setup doesn't work: Error: Request failed: 500

### ISSUE THREAD

**Issue by rabelux** [mediamonkeyserver/mms#56]
When starting mms it prints a line containing the message in the title.
Functionality isn't compromised though and others also had this issue: https://www.mediamonkey.com/forum/viewtopic.php?f=31&t=100241
Seems to be some kind of cosmetic issue?

**Comment by jirihajek** [comment]
I modified the error messages, as it really doesn't mean anything wrong for MMS functionality. Also, disabled the default NAS setup, needs to be manually enabled in Configuration first.
